// The in-app version of docs/databricks-integration-api-spec.md — every endpoint the spec
// describes, transcribed the same way that file was (see its own header), so a Databricks/Kong
// integrator has a reference inside the product instead of needing repo access. Single source
// of truth is still the markdown file; if the spec changes, update both together.
//
// `status: "live"` means a real route exists at src/app/integration/v1/<path>/route.ts and
// returns exactly this shape (deviations noted per-endpoint, e.g. /seasons' `version`).
// `status: "planned"` means this is still just the target shape — see things-to-know.md's
// Integrations section before building one; most planned `tasks` fields have no backing column
// yet.

export interface EndpointParam {
  name: string;
  description: string;
}

export interface EndpointDoc {
  method: "GET";
  path: string;
  status: "live" | "planned";
  purpose: string;
  pathParams?: EndpointParam[];
  queryParams?: EndpointParam[];
  exampleResponse: unknown;
  /** A deviation from the spec's literal shape, or another as-built caveat worth calling out
   *  right next to the example that would otherwise contradict it. **Required on every `"live"`
   *  endpoint that sends `null` for a spec field with no backing column** (name each one and
   *  say why — "no column exists" and "the column exists but means something different" are
   *  different caveats, and a consumer needs to know which). This is the one place that
   *  actually gets read before someone maps a field, so it carries the detail — the "How this
   *  works" card deliberately doesn't repeat it endpoint-by-endpoint. */
  note?: string;
}

// Shared across almost every endpoint — described once here instead of repeated verbatim on
// each of the ~15 endpoints that take the same pagination/sync params.
const PARAM_DESCRIPTIONS: Record<string, string> = {
  cursor: "Opaque pagination token from the previous response's meta.next_cursor. Omit to start from the first page.",
  page_size: "Rows per page. Default 500, max 2000.",
  updated_since: "ISO 8601 timestamp — only rows updated at or after this time (incremental sync).",
  include_deleted: '"true" to include soft-deleted rows. Default false (live rows only).',
  entity_type: 'Restrict the change feed to one entity type, e.g. "task".',
  occurred_since: "ISO 8601 timestamp — only changes recorded at or after this time.",
  season_code: "Filter by the season's stable short code, e.g. \"RES H2'26\".",
  brand_code: 'Filter by the brand\'s stable short code, e.g. "BR-A".',
  status: "Filter by status.",
  blocked_status: "Filter by blocked status.",
  priority: "Filter by priority.",
  owner_name: "Filter by owner (department or person) display name.",
  owner_id: "Filter by owner profile id.",
  escalation_owner_name: "Filter by escalation owner display name.",
  delay_reason_code: "Filter by delay reason code.",
  is_milestone: '"true" to return only milestone tasks.',
  due_from: "ISO 8601 date — lower bound (inclusive) on due_date.",
  due_to: "ISO 8601 date — upper bound (inclusive) on due_date.",
  task_id: "Restrict to one task.",
  predecessor_task_id: "Filter by the dependency's predecessor task.",
  successor_task_id: "Filter by the dependency's successor task.",
  dependency_type: 'Filter by dependency type, e.g. "finish_to_start".',
  date_from: "ISO 8601 date — lower bound (inclusive).",
  date_to: "ISO 8601 date — upper bound (inclusive).",
  snapshot_grain: 'Aggregation grain for history snapshots, e.g. "daily".',
};

// Builds the {name, description} list a row of query-param chips needs from just the param
// names — one description per name, defined once above, instead of retyping the same sentence
// on every endpoint that happens to take `cursor` or `updated_since`.
function params(...names: string[]): EndpointParam[] {
  return names.map((name) => ({ name, description: PARAM_DESCRIPTIONS[name] ?? "" }));
}

export const ENDPOINT_DOCS: EndpointDoc[] = [
  {
    method: "GET",
    path: "/health",
    status: "live",
    purpose: "Basic service health check.",
    exampleResponse: {
      status: "ok",
      service: "critical-path-integration-api",
      schema_version: "v1",
      server_time: "2026-08-02T10:15:30Z",
    },
  },
  {
    method: "GET",
    path: "/seasons",
    status: "live",
    purpose: "Season master data.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: "`version` is always null — this schema has no change-counter column, on seasons or anywhere else.",
    exampleResponse: {
      data: [
        {
          season_id: "b0455f54-d9dc-4d30-91f4-9cb31f44f745",
          season_code: "RES H2'26",
          season_name: "Winter 2026",
          status: "active",
          start_date: "2025-09-01",
          end_date: "2026-02-28",
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/changes",
    status: "live",
    purpose: "Global incremental change feed across supported entities.",
    queryParams: params("cursor", "page_size", "entity_type", "occurred_since"),
    note: "Reads audit_log, the only change-tracking table in this schema — and it only ever writes entity_type='task' rows for real operational data (it also carries entity_type='api_key' rows for this integration feature's own key lifecycle, deliberately excluded: api_key isn't a spec Core Entity, and it's an administrative event about the integration layer itself, not business data). This endpoint always scopes to entity_type='task' regardless of the query param; entity_type=anything else returns an empty page honestly, not an error — those entities just have no change tracking yet. `record` is the audit row's own stored diff payload (field-level changes / participant changes / created-with-owners, see types/audit.ts's AuditChanges), not a full current-state snapshot of the task — audit_log never stored one, and joining today's tasks row onto a historical event would misrepresent history for anything but the most recent change. `version` is always null like every endpoint. Each row's own `cursor` field and meta.next_cursor use the same opaque (created_at, id) keyset every other list endpoint uses, reused as-is even though this table's ordering field is created_at, not updated_at.",
    exampleResponse: {
      data: [
        {
          cursor: "2026-08-02T08:12:52Z_0000018842",
          entity_type: "task",
          entity_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
          operation: "updated",
          occurred_at: "2026-08-02T08:12:52Z",
          version: null,
          record: {
            task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
            task_name: "External Showing with Protos",
            changes: { fields: [{ field: "due_date", from: "2025-09-10", to: "2025-09-15" }] },
          },
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/tasks",
    status: "live",
    purpose: "Paginated task snapshot feed.",
    queryParams: params(
      "cursor",
      "page_size",
      "updated_since",
      "include_deleted",
      "season_code",
      "brand_code",
      "status",
      "blocked_status",
      "priority",
      "owner_name",
      "escalation_owner_name",
      "delay_reason_code",
      "is_milestone",
      "due_from",
      "due_to"
    ),
    note: "About a third of the fields below have no backing column and are always null: blocked_status, escalation_owner_name, assignee_name (tasks.assignee_id exists but is superseded by task_participants and about to be dropped — reading it would surface stale/misleading data, same reasoning the app's own CSV export gives for omitting it), is_milestone, milestone_flag, delay_reason_code/text, planned_*/actual_* dates, due_date_zapier, comments_count, attachments_count (no attachments table exists), link_url, version. Filters for the same absent concepts (blocked_status, escalation_owner_name, delay_reason_code, is_milestone) are accepted but are no-ops. working_timeline_start_date/end_date ARE real (tasks.start_date/end_date); duration_days is computed live from them (safe on an incremental feed since both are static stored columns, not \"today\"). days_late/days_at_risk are ALWAYS null here — unlike /reports/overdue-tasks' days_overdue, this endpoint has a real updated_since contract, and a value that silently changes day-to-day without updated_at moving would make a consumer miss it on an incremental pull. owner_name is the same joined-string idiom as every other endpoint; people_involved is a real array, not joined. calendar_sync_status is \"synced\" only when calendar_event_id is set, never \"failed\"/\"pending\" (same reasoning as /calendar-events). /tasks/{task_id} returns this exact same full shape, a superset of its own separately-sketched (and narrower) example below.",
    exampleResponse: {
      data: [
        {
          task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
          task_name: "External Showing with Protos",
          key_stage: "Range Review",
          status: "overdue",
          blocked_status: null,
          priority: "high",
          season_id: "b0455f54-d9dc-4d30-91f4-9cb31f44f745",
          season_code: "RES H2'26",
          season_name: "Winter 2026",
          brand_id: "a64f6f74-51b2-49c3-b8fd-98467f205c90",
          brand_code: "BR-A",
          brand_name: "Brand A",
          gender: "guys",
          owner_name: "Brand Managers",
          assignee_name: null,
          escalation_owner_name: null,
          people_involved: ["Brand Managers", "Design"],
          planned_start_date: null,
          planned_end_date: null,
          working_timeline_start_date: "2025-09-15",
          working_timeline_end_date: "2025-11-24",
          actual_start_date: null,
          actual_end_date: null,
          duration_days: 71,
          due_date_zapier: null,
          due_date: "2025-09-15",
          days_at_risk: null,
          days_late: null,
          is_milestone: null,
          milestone_flag: null,
          delay_reason_code: null,
          delay_reason_text: null,
          comments_count: null,
          attachments_count: null,
          notes: null,
          link_url: null,
          calendar_event_id: "6as6sv1oq874m8lanuvj01efrc",
          calendar_sync_status: "synced",
          calendar_last_synced_at: "2026-08-02T08:13:00Z",
          created_at: "2025-08-20T11:00:00Z",
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/tasks/{task_id}",
    status: "live",
    purpose: "Fetch one task by ID.",
    pathParams: [{ name: "task_id", description: "The task's UUID." }],
    note: "Same full row shape as /tasks (see its note for the field-by-field gap accounting), not the narrower field set the spec's own single-item example sketches — a deliberate deviation, since maintaining two different shapes for the same entity would drift and every field is null-filled anyway. No deleted_at filter: a soft-deleted task's id still resolves here with its real deleted_at set, rather than 404ing and hiding that it once existed. A genuinely unknown id 404s.",
    exampleResponse: {
      data: {
        task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
        task_name: "External Showing with Protos",
        key_stage: "Range Review",
        status: "overdue",
        blocked_status: null,
        priority: "high",
        season_id: "b0455f54-d9dc-4d30-91f4-9cb31f44f745",
        season_code: "RES H2'26",
        season_name: "Winter 2026",
        brand_id: "a64f6f74-51b2-49c3-b8fd-98467f205c90",
        brand_code: "BR-A",
        brand_name: "Brand A",
        gender: "guys",
        owner_name: "Brand Managers",
        assignee_name: null,
        escalation_owner_name: null,
        people_involved: ["Brand Managers", "Design"],
        planned_start_date: null,
        planned_end_date: null,
        working_timeline_start_date: "2025-09-15",
        working_timeline_end_date: "2025-11-24",
        actual_start_date: null,
        actual_end_date: null,
        duration_days: 71,
        due_date_zapier: null,
        due_date: "2025-09-15",
        days_at_risk: null,
        days_late: null,
        is_milestone: null,
        milestone_flag: null,
        delay_reason_code: null,
        delay_reason_text: null,
        comments_count: null,
        attachments_count: null,
        notes: null,
        link_url: null,
        calendar_event_id: "6as6sv1oq874m8lanuvj01efrc",
        calendar_sync_status: "synced",
        calendar_last_synced_at: "2026-08-02T08:13:00Z",
        created_at: "2025-08-20T11:00:00Z",
        updated_at: "2026-08-02T08:12:52Z",
        deleted_at: null,
        version: null,
      },
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z" },
    },
  },
  {
    method: "GET",
    path: "/brands",
    status: "live",
    purpose: "Brand master data.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: "`version` is always null — same reasoning as /seasons, no change-counter column exists.",
    exampleResponse: {
      data: [
        {
          brand_id: "a64f6f74-51b2-49c3-b8fd-98467f205c90",
          brand_code: "BR-A",
          brand_name: "Brand A",
          description: "Premium lifestyle brand",
          status: "active",
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/users",
    status: "live",
    purpose: "User master data.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: "`last_active_at` and `deleted_at` are always null — no sign-in tracking exists, and users are deactivated via `status`, never deleted. `include_deleted` is accepted but has no effect for the same reason. `version` is always null like every other endpoint. `role_name` is real (e.g. \"Administrator\"), from the same label map the UI's role badges use.",
    exampleResponse: {
      data: [
        {
          user_id: "fd7f073a-ef74-4cb2-b822-b2a943026958",
          display_name: "Oliver Smith",
          email: "oliver.smith@criticalpath.com",
          department: "IT",
          role_name: "Administrator",
          status: "active",
          last_active_at: null,
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/teams",
    status: "live",
    purpose: "Team master data.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: '"Team" means `departments` — this schema has no separate team-within-department hierarchy. `department` and `lead_name` are always null (no such concepts exist here; a department IS the team, and there is no "lead" role). `member_count`/`active_tasks_count`/`completed_tasks_count` ARE real, computed data (profiles per department; distinct tasks per department via task_participants, deduped so a department that is both owner and involved on one task is not counted twice) — not a gap like `version`. `status` is derived from `deleted_at` since departments have no separate status column.',
    exampleResponse: {
      data: [
        {
          team_id: "c0f1bbd6-85a0-46e4-8b95-f5cb2e1a5065",
          team_name: "Brand Managers",
          department: null,
          lead_name: null,
          member_count: 6,
          active_tasks_count: 101,
          completed_tasks_count: 0,
          status: "active",
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/roles",
    status: "live",
    purpose: "Role and permission master data.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: 'Maps to constants/roles.ts\'s fixed ROLE enum + lib/permissions.ts\'s allow-list matrix, not a database table — every field comes from code except user_count. `role_id` is the role\'s code (e.g. "admin"), not a UUID: there\'s no synthetic row to assign one to. `permission_key` values are this app\'s own action strings (e.g. "task.create"), not the spec\'s illustrative "tasks.create" — real source data over cosmetic conformance to the example. Per-permission `access_level` is always "full" (can() is boolean allow/deny, not graded). Role-level `access_level` is "full_access" only when a role\'s permission list covers every action (true for admin, provably) — null for the other three, since the spec names no other tier and inventing one would be guessing. `status` is always "active" (roles have no deactivation concept, unlike profiles.status). `updated_at`/`deleted_at`/`version` are always null — nothing tracks when a role\'s permission set last changed, and roles are never deleted. `updated_since`/`include_deleted` are accepted but are no-ops for the same reason. `user_count` counts every profile with that role regardless of active/inactive status, same convention as `/teams`\' member_count.',
    exampleResponse: {
      data: [
        {
          role_id: "admin",
          role_name: "Administrator",
          access_level: "full_access",
          status: "active",
          user_count: 3,
          permissions: [
            { permission_key: "task.create", access_level: "full" },
            { permission_key: "task.delete", access_level: "full" },
          ],
          updated_at: null,
          deleted_at: null,
          version: null,
        },
        {
          role_id: "external",
          role_name: "External",
          access_level: null,
          status: "active",
          user_count: 12,
          permissions: [
            { permission_key: "profile.update_own", access_level: "full" },
            { permission_key: "dashboard.view", access_level: "full" },
            { permission_key: "task.view", access_level: "full" },
          ],
          updated_at: null,
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: null, page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/calendar-events",
    status: "live",
    purpose: "Calendar sync metadata tied to tasks and due dates.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: 'One row per task, synced or not — a task never pushed to Google still appears, with `calendar_event_id`/`provider`/`sync_status`/`last_synced_at` sent as `null` rather than the row being omitted (see the second example row below). `sync_status` is `"synced"` only when `google_event_id` is set; it is never `"failed"` or `"pending"` for an unsynced task because a failed push leaves the columns untouched exactly like one never attempted (the error is swallowed) — this schema has no way to tell those two apart, so it doesn\'t claim to. `provider` is `"google_calendar"` when synced, `null` otherwise (it\'s the only provider this platform integrates with). `event_deleted` is `true` when the task is soft-deleted (best-effort signal — the Google-side delete can silently fail) and `false` for a never-synced task, since there was genuinely never an event to delete. `version` is always null like every endpoint.',
    exampleResponse: {
      data: [
        {
          calendar_event_id: "6as6sv1oq874m8lanuvj01efrc",
          task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
          task_name: "External Showing with Protos",
          provider: "google_calendar",
          season_code: "RES H2'26",
          brand_name: "Brand A",
          owner_name: "Brand Managers",
          due_date: "2025-09-15",
          sync_status: "synced",
          last_synced_at: "2026-08-02T08:13:00Z",
          event_deleted: false,
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: null,
        },
        {
          calendar_event_id: null,
          task_id: "3f1e2a4b-5c6d-47e8-9f10-1a2b3c4d5e6f",
          task_name: "Draft Internal Sign-off",
          provider: null,
          season_code: "RES H2'26",
          brand_name: null,
          owner_name: "Design",
          due_date: "2025-09-20",
          sync_status: null,
          last_synced_at: null,
          event_deleted: false,
          updated_at: "2026-08-01T09:00:00Z",
          deleted_at: null,
          version: null,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/task-dependencies",
    status: "planned",
    purpose: "Dependency data between tasks.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted", "task_id", "predecessor_task_id", "successor_task_id", "dependency_type"),
    note: "No task_dependencies table exists in this schema — the platform doesn't model task-to-task dependencies today.",
    exampleResponse: {
      data: [
        {
          dependency_id: "4d0bff3b-f590-4d80-9b9f-8a140de03c70",
          predecessor_task_id: "11111111-1111-1111-1111-111111111111",
          predecessor_task_name: "Design Brief",
          successor_task_id: "22222222-2222-2222-2222-222222222222",
          successor_task_name: "External Showing with Protos",
          dependency_type: "finish_to_start",
          lag_days: 2,
          is_blocking: true,
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: 2,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/delay-reason-codes",
    status: "planned",
    purpose: "Master list of reason codes for delay reporting.",
    queryParams: params("cursor", "page_size", "updated_since", "include_deleted"),
    note: "No delay_reason_codes table exists — delay reasons aren't tracked as structured data on a task today.",
    exampleResponse: {
      data: [
        {
          reason_code: "VENDOR_DELAY",
          label: "Vendor delay",
          description: "Third-party supplier or vendor caused a schedule delay",
          category: "external",
          active: true,
          updated_at: "2026-08-02T08:12:52Z",
          deleted_at: null,
          version: 1,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:15:30Z", next_cursor: null, page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/dashboard-summary",
    status: "live",
    purpose: "Optional summary endpoint for the dashboard headline values.",
    queryParams: params("season_code", "brand_code", "owner_id", "date_from", "date_to"),
    note: "`overdue_tasks` trusts the stored `tasks.status` column, not a live check against `due_date` — same known gap as every /reports/* endpoint (no status-rollover cron exists yet, see things-to-know.md's Tasks section). `owner_id` means a `profiles.id` specifically, unlike every other endpoint's `owner_name` — a task owned only by a department (Vendor, Supplier, ...) can never match this filter, which is correct given the spec's literal wording, not a gap. `by_status`/`by_season`/`by_brand` only include groups with at least one matching task — a status/season/brand with zero results after filtering is omitted, not sent as a zeroed-out row. `by_brand` under-counts relative to `totals.total_tasks` for the same reason /reports/tasks-by-brand does: `tasks.brand_id` is nullable, so a task with no brand contributes to no group. Not paginated — no cursor/page_size, since this is one aggregate object, not a row list; `as_of` and `generated_at` are the same instant.",
    exampleResponse: {
      data: {
        as_of: "2026-08-02T10:30:00Z",
        generated_at: "2026-08-02T10:30:05Z",
        metric_definition_version: "v1",
        filters: { season_code: null, brand_code: null, owner_id: null, date_from: "2026-08-01", date_to: "2026-08-31" },
        totals: { total_tasks: 128, completed_tasks: 45, in_progress_tasks: 58, overdue_tasks: 25, completion_rate: 35.2 },
        breakdowns: {
          by_status: [{ status: "completed", count: 45 }],
          by_season: [{ season_code: "RES H2'26", count: 420, percent: 33.7 }],
          by_brand: [{ brand_name: "Brand A", count: 420, percent: 33.7 }],
        },
      },
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z" },
    },
  },
  {
    method: "GET",
    path: "/reports/task-summary",
    status: "live",
    purpose: "Optional report summary endpoint for filtered report views.",
    queryParams: params("date_from", "date_to", "season_code", "brand_code", "owner_name", "status"),
    note: "Same shape and gaps as /dashboard-summary (overdue_tasks trusts stored tasks.status; by_brand under-counts against totals.total_tasks since tasks.brand_id is nullable), plus a fourth breakdown, by_owner, dashboard-summary doesn't have. Unlike /dashboard-summary's owner_id (a profiles.id only), owner_name here matches a department or person by display name, same as /reports/overdue-tasks and the tasks-by-* reports. by_owner groups on the same joined owner_name string those endpoints already surface per task (departments first, then people, alphabetical, comma-joined for multi-owner tasks) — a task jointly owned by two parties is its own bucket, not split into two; a task with no owner participant at all is omitted from by_owner entirely. by_status/by_season/by_brand/by_owner all omit empty groups rather than zero-filling them. Not paginated — no cursor/page_size, one aggregate object; as_of and generated_at are the same instant.",
    exampleResponse: {
      data: {
        as_of: "2026-08-02T10:30:00Z",
        generated_at: "2026-08-02T10:30:05Z",
        metric_definition_version: "v1",
        filters: { date_from: "2026-05-01", date_to: "2026-05-31", season_code: null, brand_code: null, owner_name: null, status: null },
        totals: { total_tasks: 248, completed_tasks: 98, in_progress_tasks: 65, overdue_tasks: 10 },
        breakdowns: {
          by_status: [{ status: "completed", count: 98 }],
          by_season: [{ season_code: "RES H2'26", count: 42, percent: 16.9 }],
          by_brand: [{ brand_name: "Brand A", count: 30, percent: 12.1 }],
          by_owner: [{ owner_name: "Brand Managers", count: 25, percent: 10.1 }],
        },
      },
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z" },
    },
  },
  {
    method: "GET",
    path: "/reports/overdue-tasks",
    status: "live",
    purpose: "Optional report endpoint for overdue task lists.",
    queryParams: params("cursor", "page_size", "season_code", "brand_code", "owner_name", "due_from", "due_to"),
    note: '`status` is always `"overdue"` because that\'s the filter this endpoint runs — but it means this list trusts the stored `tasks.status` column, NOT a live check against `due_date`. Nothing in this schema auto-stamps a task `overdue` yet (no status-rollover cron exists), so a task whose due date has passed but hasn\'t been manually re-statused will not appear here — see things-to-know.md\'s Tasks section ("Is never overdue"). `days_overdue` is computed live (calendar days from `due_date` to today) since this endpoint has no `updated_since`/incremental contract — it\'s a fresh report, not a sync feed. `season_code`/`brand_code`/`owner_name` filters resolve to the underlying record first (exact match), so a code or name that matches nothing returns an empty list rather than an error.',
    exampleResponse: {
      data: [
        {
          task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
          task_name: "External Showing with Protos",
          season_code: "RES H2'26",
          brand_name: "Brand A",
          owner_name: "Brand Managers",
          due_date: "2025-09-15",
          status: "overdue",
          days_overdue: 3,
          updated_at: "2026-08-02T08:12:52Z",
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/reports/blocked-tasks",
    status: "planned",
    purpose: "Optional report endpoint for blocked task lists.",
    queryParams: params("cursor", "page_size", "season_code", "brand_code", "owner_name", "blocked_status", "escalation_owner_name", "delay_reason_code"),
    exampleResponse: {
      data: [
        {
          task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
          task_name: "External Showing with Protos",
          key_stage: "Range Review",
          owner_name: "Brand Managers",
          people_involved: ["Brand Managers", "Design"],
          blocked_status: "blocked",
          escalation_owner_name: "Oliver Smith",
          delay_reason_code: "VENDOR_DELAY",
          days_at_risk: 4,
          days_late: 3,
          due_date: "2025-09-15",
          updated_at: "2026-08-02T08:12:52Z",
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
  {
    method: "GET",
    path: "/reports/tasks-by-season",
    status: "live",
    purpose: "Optional report endpoint for season-level grouped metrics.",
    queryParams: params("date_from", "date_to", "brand_code", "owner_name", "status"),
    note: 'Not paginated — no cursor/page_size, since the row count is bounded by the number of seasons (28 today), not tasks; `meta` is the smaller { schema_version, as_of } shape. `overdue_count` has the same known gap as /reports/overdue-tasks: it trusts stored `tasks.status`, not a live due_date check. `date_from`/`date_to` filter on `due_date`; omitted, every non-deleted task counts regardless of whether it even has a due_date (matching the dashboard\'s own season breakdown, which isn\'t due-date-windowed). Only seasons with at least one matching task are returned — a season with zero results after filtering just doesn\'t appear, it isn\'t sent as a zeroed-out row.',
    exampleResponse: {
      data: [
        {
          season_id: "b0455f54-d9dc-4d30-91f4-9cb31f44f745",
          season_code: "RES H2'26",
          season_name: "Winter 2026",
          task_count: 248,
          completed_count: 98,
          in_progress_count: 65,
          overdue_count: 10,
          completion_rate: 39.5,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z" },
    },
  },
  {
    method: "GET",
    path: "/reports/tasks-by-brand",
    status: "live",
    purpose: "Optional report endpoint for brand-level grouped metrics.",
    queryParams: params("date_from", "date_to", "season_code", "owner_name", "status"),
    note: "Same shape and same caveats as /reports/tasks-by-season (not paginated, overdue_count trusts stored status). One further gap specific to this endpoint: tasks.brand_id is nullable — plenty of stage work isn't brand-specific — so a task with no brand contributes to NO group here. Summing every group's task_count will not equal the total task count for the same filters; there is no \"unbranded\" bucket in the spec to put those tasks in.",
    exampleResponse: {
      data: [
        {
          brand_id: "a64f6f74-51b2-49c3-b8fd-98467f205c90",
          brand_code: "BR-A",
          brand_name: "Brand A",
          task_count: 128,
          completed_count: 52,
          in_progress_count: 38,
          overdue_count: 10,
          completion_rate: 40.6,
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z" },
    },
  },
  {
    method: "GET",
    path: "/task-history-snapshots",
    status: "planned",
    purpose: "Historical snapshots for trend charts over time.",
    queryParams: params("cursor", "page_size", "task_id", "season_code", "brand_code", "owner_name", "date_from", "date_to", "snapshot_grain"),
    note: "No task_history_snapshots table exists — this platform doesn't retain daily point-in-time snapshots of a task today.",
    exampleResponse: {
      data: [
        {
          snapshot_date: "2026-07-25",
          task_id: "8d4a29e9-c1c4-4b80-b66b-eeb0b6277f3a",
          task_name: "External Showing with Protos",
          key_stage: "Range Review",
          owner_name: "Brand Managers",
          people_involved: ["Brand Managers", "Design"],
          planned_start_date: "2025-09-15",
          planned_end_date: "2025-11-24",
          working_timeline_start_date: "2025-09-15",
          working_timeline_end_date: "2025-11-24",
          actual_start_date: "2025-09-16",
          actual_end_date: null,
          duration_days: 70,
          due_date_zapier: "2025-09-15",
          due_date: "2025-09-15",
          status: "in_progress",
          blocked_status: "blocked",
          days_at_risk: 4,
          days_late: 3,
          is_milestone: true,
          milestone_flag: "critical_milestone",
          escalation_owner_name: "Oliver Smith",
          delay_reason_code: "VENDOR_DELAY",
        },
      ],
      meta: { schema_version: "v1", as_of: "2026-08-02T10:30:00Z", next_cursor: "opaque-cursor-value", page_size: 500 },
    },
  },
];
